xan cat rows /store/medialex/reproduction_wlwf/data_source/congress/lr/*.csv |  xan filter 'not(retweeted_id)' |  xan frequency -s user_id -l 0 | xan stats -q -s count | xan select count,sum,mean,median,min,max | xan transform mean 'round' | xan map 'sum / 268' mean_day | xan transform mean_day 'round' -o data_prod/figures/congress_lr.csv
xan cat rows /store/medialex/reproduction_wlwf/data_source/congress/majority/*.csv |  xan filter 'not(retweeted_id)' |  xan frequency -s user_id -l 0 | xan stats -q -s count | xan select count,sum,mean,median,min,max | xan transform mean 'round' | xan map 'sum / 268' mean_day | xan transform mean_day 'round' -o data_prod/figures/congress_majority.csv
xan cat rows /store/medialex/reproduction_wlwf/data_source/congress/nupes/*.csv |  xan filter 'not(retweeted_id)' | xan frequency -s user_id -l 0 | xan stats -q -s count | xan select count,sum,mean,median,min,max | xan transform mean 'round' | xan map 'sum / 268' mean_day | xan transform mean_day 'round' -o data_prod/figures/congress_nupes.csv
xan cat rows /store/medialex/reproduction_wlwf/data_source/congress/rn/*.csv |  xan filter 'not(retweeted_id)' | xan frequency -s user_id -l 0 | xan stats -q -s count | xan select count,sum,mean,median,min,max | xan transform mean 'round' | xan map 'sum / 268' mean_day | xan transform mean_day 'round' -o data_prod/figures/congress_rn.csv
xan cat rows data_prod/figures/congress_*.csv | xan map 'split("lr,maj,nupes,rn", ",")' group | xan explode group | xan slice -i 0,5,10,15 | xan select group,count,sum,mean,median,min,max,mean_day | xan transpose | xan map 'lr + maj + nupes+ rn' total | xan transpose -o "data_prod/figures/congress_tot.csv"

xan cat rows /store/medialex/reproduction_wlwf/data_source/congress/lr/*.csv |  xan filter 'not(retweeted_id)' |  xan frequency -s user_screen_name -l 5 | xan select value,count | xan slice -s 0 -l 5 | xan v
xan cat rows /store/medialex/reproduction_wlwf/data_source/congress/majority/*.csv |  xan filter 'not(retweeted_id)' |  xan frequency -s user_screen_name -l 5 | xan select value,count | xan slice -s 0 -l 5 | xan v
xan cat rows /store/medialex/reproduction_wlwf/data_source/congress/nupes/*.csv |  xan filter 'not(retweeted_id)' |  xan frequency -s user_screen_name -l 5 | xan select value,count | xan slice -s 0 -l 5 | xan v
xan cat rows /store/medialex/reproduction_wlwf/data_source/congress/rn/*.csv |  xan filter 'not(retweeted_id)' |  xan frequency -s user_screen_name -l 5 | xan select value,count | xan slice -s 0 -l 5 | xan v

xan cat rows /store/medialex/reproduction_wlwf/data_source/supporter/lr/*.csv |  xan filter 'not(retweeted_id)' |  xan frequency -s user_id -l 0 | xan stats -q -s count | xan select count,sum,mean,median,min,max | xan transform mean 'round' | xan map 'sum / 268' mean_day | xan transform mean_day 'round' -o data_prod/figures/supp_lr.csv
xan cat rows /store/medialex/reproduction_wlwf/data_source/supporter/majority/*.csv |  xan filter 'not(retweeted_id)' |  xan frequency -s user_id -l 0 | xan stats -q -s count | xan select count,sum,mean,median,min,max | xan transform mean 'round' | xan map 'sum / 268' mean_day | xan transform mean_day 'round' -o data_prod/figures/supp_majority.csv
xan cat rows /store/medialex/reproduction_wlwf/data_source/supporter/nupes/*.csv |  xan filter 'not(retweeted_id)' | xan frequency -s user_id -l 0 | xan stats -q -s count | xan select count,sum,mean,median,min,max | xan transform mean 'round' | xan map 'sum / 268' mean_day | xan transform mean_day 'round' -o data_prod/figures/supp_nupes.csv
xan cat rows /store/medialex/reproduction_wlwf/data_source/supporter/rn/*.csv |  xan filter 'not(retweeted_id)' | xan frequency -s user_id -l 0 | xan stats -q -s count | xan select count,sum,mean,median,min,max | xan transform mean 'round' | xan map 'sum / 268' mean_day | xan transform mean_day 'round' -o data_prod/figures/supp_rn.csv
xan cat rows data_prod/figures/supp_*.csv | xan map 'split("lr,maj,nupes,rn", ",")' group | xan explode group | xan slice -i 0,5,10,15 | xan select group,count,sum,mean,median,min,max,mean_day | xan transpose | xan map 'lr + maj + nupes+ rn' total | xan transpose -o "data_prod/figures/supp_tot.csv"